ALTER TABLE "verification_sessions" ADD COLUMN "method" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "publicCode" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "returnUrl" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "codeExpiresAt" DATETIME;
ALTER TABLE "verification_sessions" ADD COLUMN "resendCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "verification_sessions" ADD COLUMN "vkState" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "vkCodeVerifierEncrypted" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "vkCodeChallenge" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "vkUserId" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "vkEmail" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "vkFirstName" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "vkLastName" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "vkRawUserJson" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "lastErrorCode" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "lastErrorMessage" TEXT;
ALTER TABLE "verification_sessions" ADD COLUMN "verifiedAt" DATETIME;

CREATE UNIQUE INDEX "verification_sessions_publicCode_key" ON "verification_sessions"("publicCode");
CREATE UNIQUE INDEX "verification_sessions_vkState_key" ON "verification_sessions"("vkState");
CREATE INDEX "verification_sessions_method_status_idx" ON "verification_sessions"("method", "status");
CREATE INDEX "verification_sessions_codeExpiresAt_idx" ON "verification_sessions"("codeExpiresAt");
