import { ApiError, handleApiError, ok, readJson } from "@/lib/api";
import { getCurrentUser } from "@/lib/auth";
import { RESTAURANT_STATUSES } from "@/lib/constants";
import { prisma } from "@/lib/db";
import { requireRestaurantAccess } from "@/lib/permissions";
import { restaurantDataFromPayload } from "@/lib/restaurant-data";
import { restaurantSchema } from "@/lib/validation";
type C = { params: Promise<{ restaurantId: string }> };
export async function GET(_request: Request, context: C) { try { const { restaurantId } = await context.params; const restaurant = await prisma.restaurant.findFirst({ where: { OR: [{ id: restaurantId }, { slug: restaurantId }], isActive: true, status: RESTAURANT_STATUSES.APPROVED }, include: { workingHours: { orderBy: { dayOfWeek: "asc" } }, menuCategories: { where: { isActive: true }, orderBy: { sortOrder: "asc" }, include: { items: { where: { isAvailable: true }, orderBy: { sortOrder: "asc" } } } }, halls: { where: { isActive: true }, orderBy: { sortOrder: "asc" }, include: { tables: { where: { isActive: true }, orderBy: [{ y: "asc" }, { x: "asc" }] } } } } }); if (!restaurant) throw new ApiError(404, "Restaurant not found"); return ok({ restaurant }); } catch (error) { return handleApiError(error); } }
export async function PUT(request: Request, context: C) { try { const { restaurantId } = await context.params; const user = await getCurrentUser(); if (!user) throw new ApiError(401, "Authentication required"); const current = await requireRestaurantAccess(user, restaurantId); const payload = restaurantSchema.parse(await readJson(request)); const data = await restaurantDataFromPayload({ ...payload, status: payload.status || current.status, isActive: payload.isActive ?? current.isActive }, current.id); const restaurant = await prisma.restaurant.update({ where: { id: current.id }, data }); return ok({ restaurant }); } catch (error) { return handleApiError(error); } }
export async function DELETE(_request: Request, context: C) { try { const { restaurantId } = await context.params; const user = await getCurrentUser(); if (!user) throw new ApiError(401, "Authentication required"); const restaurant = await requireRestaurantAccess(user, restaurantId); const updated = await prisma.restaurant.update({ where: { id: restaurant.id }, data: { isActive: false } }); return ok({ restaurant: updated }); } catch (error) { return handleApiError(error); } }
